# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20171202_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='meal',
            field=models.CharField(choices=[(b'BR', b'Breakfast'), (b'LU', b'Lunch'), (b'DI', b'Dinner'), (b'OT', b'Other')], default='OT', max_length=2),
        ),
    ]
